spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 8637
  jpa:
    hibernate:
      ddl-auto: create   # 실행마다 DB 테이블 재생성
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always       # 항상 data.sql 실행

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: Fj9utiukO/Xl4cLycWatYJMzqzrGMdo1Rws/EgjdRMY+pXfR26CzsZIGya9voPOu+Uc/+AOBuSfN4nGVAfWPIg==
  access-token-expiration-ms: 3600000 # 1시간
  refresh-token-expiration-ms: 604800000 # 7일
